sudo: required
dist: trusty

language: cpp

os:
    - linux
    - osx

git:
    depth: 5

before_install:
    # LINUX
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then "./ci/travisci-beforeinstall-linux.sh" fi
    # OSX
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then "./ci/travisci-beforeinstall-osx.sh" fi

compiler:
    - clang
    - gcc

branches:
    only:
        - master

script:
    # LINUX
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then "./ci/travisci-script-linux.sh" fi
    # OSX
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then "./ci/travisci-script-osx.sh" fi