sudo: required
dist: trusty

language: cpp

os:
    - linux
    - osx

git:
    depth: 5

before_install:
    # LINUX
    - if [ $TRAVIS_OS_NAME == "linux" ]; then export DEBIAN_FRONTEND=noninteractive fi
    - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update --fix-missing fi
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        sudo apt-get install -qq
            clang
            libfreetype6-dev
            libx11-dev
            libxinerama-dev
            libxrandr-dev
            libxcursor-dev
            libxcomposite-dev
            mesa-common-dev
            libasound2-dev
            freeglut3-dev
            libcurl4-gnutls-dev+
            libasound2-dev
            libjack-dev
      fi
    - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update --fix-missing fi
    - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update -qq fi
    # OSX
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake; fi

compiler:
    - clang
    - gcc

branches:
    only:
        - master

script:
    # LINUX
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        make -C extras/UnitTestRunner/Builds/LinuxMakefile JUCE_STRING_UTF_TYPE=8
        ./extras/UnitTestRunner/Builds/LinuxMakefile/build/UnitTestRunner
        make -C extras/UnitTestRunner/Builds/LinuxMakefile clean
        make -C extras/UnitTestRunner/Builds/LinuxMakefile JUCE_STRING_UTF_TYPE=16
        ./extras/UnitTestRunner/Builds/LinuxMakefile/build/UnitTestRunner
        make -C extras/UnitTestRunner/Builds/LinuxMakefile clean
        make -C extras/UnitTestRunner/Builds/LinuxMakefile JUCE_STRING_UTF_TYPE=32
        ./extras/UnitTestRunner/Builds/LinuxMakefile/build/UnitTestRunner
        make -C extras/UnitTestRunner/Builds/LinuxMakefile clean
      fi
    # OSX
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        xcodebuild -project extras/UnitTestRunner/Builds/MacOSX/UnitTestRunner.xcodeproj
      fi